# https://docs.codecov.com/docs/codecovyml-reference

ignore:
  - "**/__tests__/**" 
  - deps.ts
  - dev_deps.ts

coverage:
  status:
    project:
      default: 
        threshold: 20%
    patch:
      default: 
        threshold: 20%
